(function () {
  "use strict";

  var cfg = window.CMS1990;
  firebase.initializeApp(cfg.firebase);
  var auth = firebase.auth();
  var db = firebase.firestore();
  var FV = firebase.firestore.FieldValue;
  var state = { user: null, pageId: "ldp01", defaults: {}, defaultSeo: {}, publishedDoc: {}, draftDoc: {}, content: {}, seo: {}, integrations: {}, dirty: false, integrationDirty: false, leads: [], leadRef: null };
  var $ = function (id) { return document.getElementById(id); };
  var titles = { dashboard: "Tổng quan", content: "Nội dung LDP", integrations: "SEO & Tích hợp", leads: "Quản lý lead", versions: "Lịch sử phiên bản", team: "Đội ngũ & quyền" };

  function esc(value) { return String(value == null ? "" : value).replace(/[&<>\"']/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]; }); }
  function toast(message, isError) { var el = $("toast"); el.textContent = message; el.className = "toast show" + (isError ? " error" : ""); clearTimeout(toast.timer); toast.timer = setTimeout(function () { el.className = "toast"; }, 3200); }
  function errorMessage(err) { console.error(err); return err && err.message ? err.message.replace(/^Firebase:\s*/i, "") : "Có lỗi xảy ra."; }
  function time(value) { if (!value) return "—"; var d = value.toDate ? value.toDate() : new Date(value); return isNaN(d) ? "—" : new Intl.DateTimeFormat("vi-VN", { dateStyle: "short", timeStyle: "short" }).format(d); }
  function labelFor(key) { var names = { hero:"Hero", form:"Form", faq:"FAQ", cases:"Case study", case:"Case study", diag:"Chẩn đoán", diff:"Khác biệt", pain:"Nỗi đau", proof:"Bằng chứng", testi:"Đánh giá", final:"CTA cuối", quiz:"Quiz", signal:"Signal", truth:"Sự thật", cta:"CTA" }; var parts = key.split("."); return (names[parts[0]] || parts[0]) + " · " + parts.slice(1).join(" · "); }
  function statusLabel(status) { return { new:"Mới", contacted:"Đã liên hệ", qualified:"Tiềm năng", won:"Thành công", lost:"Không phù hợp" }[status || "new"] || status; }
  function pageOptions(select) { select.innerHTML = Object.keys(cfg.pages).map(function (id) { return '<option value="' + id + '">' + esc(cfg.pages[id].name) + '</option>'; }).join(""); }

  pageOptions($("contentPage")); pageOptions($("integrationPage")); pageOptions($("leadPage")); pageOptions($("versionPage"));

  $("loginBtn").onclick = function () { auth.signInWithPopup(new firebase.auth.GoogleAuthProvider()).catch(function (e) { toast(errorMessage(e), true); }); };
  $("logoutBtn").onclick = function () { auth.signOut(); };
  $("menuBtn").onclick = function () { document.querySelector(".sidebar").classList.toggle("open"); };
  $("copyUid").onclick = function () { navigator.clipboard.writeText(state.user.uid).then(function () { toast("Đã sao chép UID."); }); };

  auth.onAuthStateChanged(async function (user) {
    if (!user) { state.user = null; $("login").classList.remove("hidden"); $("app").classList.add("hidden"); return; }
    try {
      var email = (user.email || "").toLowerCase();
      if (email === cfg.bootstrapEmail.toLowerCase()) {
        await db.collection("cms_admins").doc(user.uid).set({ email: email, displayName: user.displayName || "", role: "owner", active: true, updatedAt: FV.serverTimestamp() }, { merge: true });
      } else {
        var access = await db.collection("cms_admins").doc(user.uid).get();
        if (!access.exists || access.data().active !== true) throw new Error("Tài khoản chưa được cấp quyền CMS. Hãy gửi UID cho Owner: " + user.uid);
      }
      state.user = user;
      $("userName").textContent = user.displayName || "Thành viên 1990"; $("helloName").textContent = (user.displayName || "1990").split(" ").slice(-1)[0]; $("userEmail").textContent = user.email || ""; $("currentUid").textContent = user.uid;
      $("login").classList.add("hidden"); $("app").classList.remove("hidden");
      await Promise.all([loadDashboard(), loadContent("ldp01"), loadTeam()]);
    } catch (e) { toast(errorMessage(e), true); await auth.signOut(); }
  });

  document.querySelectorAll("[data-view]").forEach(function (button) { button.onclick = function () { showView(button.dataset.view); }; });
  document.querySelectorAll("[data-go]").forEach(function (button) { button.onclick = function () { showView(button.dataset.go); }; });
  function showView(name) {
    document.querySelectorAll(".view").forEach(function (v) { v.classList.toggle("active", v.id === "view-" + name); });
    document.querySelectorAll(".nav-item").forEach(function (b) { b.classList.toggle("active", b.dataset.view === name); });
    $("viewTitle").textContent = titles[name]; document.querySelector(".sidebar").classList.remove("open");
    if (name === "integrations") loadIntegration($("integrationPage").value || state.pageId); if (name === "leads") loadLeads(); if (name === "versions") loadVersions(); if (name === "team") loadTeam();
  }

  async function loadDashboard() {
    try {
      var result = await Promise.all(Object.keys(cfg.pages).map(function (id) { return db.collection(cfg.pages[id].collection).orderBy("submittedAt", "desc").limit(150).get(); }));
      var all = [];
      result.forEach(function (snap, index) { var id = Object.keys(cfg.pages)[index]; snap.forEach(function (doc) { all.push(Object.assign({ _id: doc.id, _pageId: id }, doc.data())); }); });
      all.sort(function (a, b) { return ((b.submittedAt && b.submittedAt.seconds) || 0) - ((a.submittedAt && a.submittedAt.seconds) || 0); });
      $("statLead1").textContent = result[0].size; $("statLead2").textContent = result[1].size; $("statPending").textContent = all.filter(function (l) { return !l.cms_status || l.cms_status === "new"; }).length;
      $("recentLeads").innerHTML = all.slice(0, 8).map(function (lead) { return '<tr><td><strong>' + esc(lead.fullname) + '</strong><small>' + esc(lead.phone || lead.email) + '</small></td><td>' + esc(cfg.pages[lead._pageId].short) + '</td><td>' + esc(lead.utm_source || lead.ref || "Trực tiếp") + '</td><td>' + time(lead.submittedAt) + '</td><td><span class="badge ' + esc(lead.cms_status || "new") + '">' + esc(statusLabel(lead.cms_status)) + '</span></td></tr>'; }).join("") || '<tr><td colspan="5" class="empty">Chưa có lead.</td></tr>';
    } catch (e) { toast("Không tải được tổng quan: " + errorMessage(e), true); }
  }

  $("contentPage").onchange = function () { loadContent(this.value); };
  $("contentSearch").oninput = renderContentFields;
  $("previewFrame").onload = function () { setTimeout(requestSnapshot, 700); };
  window.addEventListener("message", function (event) {
    var expected = new URL(cfg.pages[state.pageId].preview).origin;
    if (event.origin !== expected || !event.data || event.data.type !== "LP1990_CMS_SNAPSHOT" || event.data.pageId !== state.pageId) return;
    state.defaults = event.data.content || {}; state.defaultSeo = event.data.seo || {}; mergeContent();
  });
  function requestSnapshot() { var frame = $("previewFrame"); if (frame.contentWindow) frame.contentWindow.postMessage({ type:"LP1990_CMS_REQUEST_SNAPSHOT" }, new URL(cfg.pages[state.pageId].preview).origin); }
  async function loadContent(pageId) {
    state.pageId = pageId; state.defaults = {}; state.defaultSeo = {}; state.publishedDoc = {}; state.draftDoc = {}; state.content = {}; state.seo = {}; state.integrations = {}; state.dirty = false; state.integrationDirty = false; $("contentPage").value = pageId; $("integrationPage").value = pageId; $("saveState").textContent = "Đang tải…"; $("contentFields").innerHTML = '<div class="empty">Đang đọc nội dung LDP…</div>';
    var url = cfg.pages[pageId].preview; $("previewFrame").src = url; $("openPreview").href = url;
    try { var docs = await Promise.all([db.collection("cms_public").doc(pageId).get(), db.collection("cms_drafts").doc(pageId).get()]); state.publishedDoc = docs[0].exists ? docs[0].data() : {}; state.draftDoc = docs[1].exists ? docs[1].data() : {}; mergeContent(); } catch (e) { toast(errorMessage(e), true); }
  }
  function defaultIntegrations(pageId) { var page = cfg.pages[pageId]; return { sheetsEnabled:!!page.sheetWebhookUrl, sheetDocumentUrl:page.sheetUrl || "", sheetTabName:page.sheetTab || "", sheetsWebhookUrl:page.sheetWebhookUrl || "", trackingEnabled:false, gtmId:"", ga4Id:"", metaPixelId:"", tiktokPixelId:"", mailchimpScriptUrl:page.mailchimpScriptUrl || "" }; }
  function mergeContent() { var integrationDefaults=defaultIntegrations(state.pageId);state.content = Object.assign({}, state.defaults, state.publishedDoc.content || {}, state.draftDoc.content || {}); state.seo = Object.assign({}, state.defaultSeo, state.publishedDoc.seo || {}, state.draftDoc.seo || {}); state.integrations = Object.assign({},integrationDefaults, state.publishedDoc.integrations || {}, state.draftDoc.integrations || {});if(!state.integrations.sheetsWebhookUrl||state.integrations.sheetsWebhookUrl.indexOf("YOUR_GOOGLE_APPS_SCRIPT_WEB_APP_URL")>=0){state.integrations.sheetsEnabled=integrationDefaults.sheetsEnabled;state.integrations.sheetsWebhookUrl=integrationDefaults.sheetsWebhookUrl;state.integrations.sheetTabName=integrationDefaults.sheetTabName;} renderContentFields(); fillIntegrationForm(); state.dirty = false; state.integrationDirty = false; $("saveState").textContent = Object.keys(state.draftDoc).length ? "Đã tải bản nháp" : "Đang dùng bản đã xuất bản"; $("integrationState").textContent = Object.keys(state.draftDoc).length ? "Đã tải bản nháp" : "Đang dùng bản đã xuất bản"; sendPreview(); }
  function renderContentFields() {
    var root = $("contentFields"), query = ($("contentSearch").value || "").toLowerCase(); var keys = Object.keys(state.content).sort(); if (query) keys = keys.filter(function (k) { return k.toLowerCase().indexOf(query) >= 0 || labelFor(k).toLowerCase().indexOf(query) >= 0; });
    root.innerHTML = ""; if (!keys.length) { root.innerHTML = '<div class="empty">Không tìm thấy trường nội dung.</div>'; return; }
    var groups = {}; keys.forEach(function (key) { var groupKey=key.split(".")[0]; (groups[groupKey]||(groups[groupKey]=[])).push(key); });
    Object.keys(groups).forEach(function(groupKey,index){var details=document.createElement("details");details.className="content-group";details.open=!!query||index<2;var summary=document.createElement("summary");summary.innerHTML='<span>'+esc(labelFor(groupKey+".section").split(" · ")[0])+'</span><span class="content-group-count">'+groups[groupKey].length+' trường</span>';var fields=document.createElement("div");fields.className="content-group-fields";groups[groupKey].forEach(function (key) { var wrap = document.createElement("div"); wrap.className = "content-field"; var label = document.createElement("label"); label.textContent = labelFor(key); var code = document.createElement("small"); code.textContent = key; label.appendChild(code); var area = document.createElement("textarea"); area.rows = Math.min(8, Math.max(2, Math.ceil(String(state.content[key] || "").length / 70))); area.value = state.content[key] || ""; area.dataset.key = key; area.addEventListener("input", function () { state.content[key] = area.value; state.dirty = true; $("saveState").textContent = "Có thay đổi chưa lưu"; }); wrap.appendChild(label); wrap.appendChild(area); fields.appendChild(wrap); });details.appendChild(summary);details.appendChild(fields);root.appendChild(details);});
  }
  function sendPreview() { var frame = $("previewFrame"), origin = new URL(cfg.pages[state.pageId].preview).origin; if (frame.contentWindow) frame.contentWindow.postMessage({ type:"LP1990_CMS_PREVIEW", pageId:state.pageId, content:state.content, seo:state.seo, integrations:state.integrations }, origin); }
  $("previewBtn").onclick = function () { sendPreview(); toast("Đã cập nhật khung xem thử. Chưa xuất bản."); };
  function editorPayload(){return {content:state.content,seo:state.seo,integrations:state.integrations,updatedAt:FV.serverTimestamp(),updatedBy:state.user.email};}
  $("saveDraftBtn").onclick = async function () { try { await db.collection("cms_drafts").doc(state.pageId).set(editorPayload(), { merge:true }); state.dirty=false; $("saveState").textContent="Đã lưu bản nháp"; toast("Đã lưu bản nháp."); } catch(e){ toast(errorMessage(e),true); } };
  $("publishBtn").onclick = async function () {
    if (!Object.keys(state.content).length) return toast("Chưa có nội dung để xuất bản.", true);
    if (!confirm("Xuất bản nội dung này lên " + cfg.pages[state.pageId].name + "?")) return;
    try { var batch=db.batch(), publicRef=db.collection("cms_public").doc(state.pageId), draftRef=db.collection("cms_drafts").doc(state.pageId), versionRef=db.collection("cms_versions").doc(state.pageId).collection("items").doc(); var payload=editorPayload(); batch.set(publicRef,payload); batch.set(draftRef,payload,{merge:true}); batch.set(versionRef,{content:state.content,seo:state.seo,integrations:state.integrations,createdAt:FV.serverTimestamp(),createdBy:state.user.email}); await batch.commit(); state.publishedDoc={content:Object.assign({},state.content),seo:Object.assign({},state.seo),integrations:Object.assign({},state.integrations)}; state.dirty=false; state.integrationDirty=false; $("saveState").textContent="Đã xuất bản"; $("integrationState").textContent="Đã xuất bản"; toast("Xuất bản thành công. LDP sẽ nhận nội dung và cấu hình mới khi tải lại."); } catch(e){toast(errorMessage(e),true);}
  };

  var integrationFields = { seoTitle:["seo","title"], seoDescription:["seo","description"], seoImage:["seo","image"], seoCanonical:["seo","canonical"], sheetsEnabled:["integrations","sheetsEnabled"], sheetDocumentUrl:["integrations","sheetDocumentUrl"], sheetTabName:["integrations","sheetTabName"], sheetsWebhookUrl:["integrations","sheetsWebhookUrl"], trackingEnabled:["integrations","trackingEnabled"], gtmId:["integrations","gtmId"], ga4Id:["integrations","ga4Id"], metaPixelId:["integrations","metaPixelId"], tiktokPixelId:["integrations","tiktokPixelId"], mailchimpScriptUrl:["integrations","mailchimpScriptUrl"] };
  Object.keys(integrationFields).forEach(function(id){var el=$(id);el.addEventListener(el.type==="checkbox"?"change":"input",function(){readIntegrationForm();state.integrationDirty=true;$("integrationState").textContent="Có thay đổi chưa lưu";$("integrationState").classList.add("integration-dirty");updateIntegrationHealth();});});
  $("integrationPage").onchange=function(){loadIntegration(this.value);};
  $("seoDescription").oninput=function(){readIntegrationForm();$("seoDescriptionCount").textContent=this.value.length+" / 160 ký tự khuyến nghị";state.integrationDirty=true;$("integrationState").textContent="Có thay đổi chưa lưu";updateIntegrationHealth();};

  async function loadIntegration(pageId){if(pageId!==state.pageId||!Object.keys(state.content).length)await loadContent(pageId);else fillIntegrationForm();}
  function fillIntegrationForm(){
    var data={seoTitle:state.seo.title||"",seoDescription:state.seo.description||"",seoImage:state.seo.image||"",seoCanonical:state.seo.canonical||"",sheetsEnabled:!!state.integrations.sheetsEnabled,sheetDocumentUrl:state.integrations.sheetDocumentUrl||"",sheetTabName:state.integrations.sheetTabName||"",sheetsWebhookUrl:state.integrations.sheetsWebhookUrl||"",trackingEnabled:!!state.integrations.trackingEnabled,gtmId:state.integrations.gtmId||"",ga4Id:state.integrations.ga4Id||"",metaPixelId:state.integrations.metaPixelId||"",tiktokPixelId:state.integrations.tiktokPixelId||"",mailchimpScriptUrl:state.integrations.mailchimpScriptUrl||""};
    Object.keys(data).forEach(function(id){var el=$(id);if(!el)return;if(el.type==="checkbox")el.checked=data[id];else el.value=data[id];});$("seoDescriptionCount").textContent=String(data.seoDescription).length+" / 160 ký tự khuyến nghị";updateIntegrationHealth();
  }
  function readIntegrationForm(){state.seo={title:$("seoTitle").value.trim(),description:$("seoDescription").value.trim(),image:$("seoImage").value.trim(),canonical:$("seoCanonical").value.trim()};state.integrations={sheetsEnabled:$("sheetsEnabled").checked,sheetDocumentUrl:$("sheetDocumentUrl").value.trim(),sheetTabName:$("sheetTabName").value.trim(),sheetsWebhookUrl:$("sheetsWebhookUrl").value.trim(),trackingEnabled:$("trackingEnabled").checked,gtmId:$("gtmId").value.trim().toUpperCase(),ga4Id:$("ga4Id").value.trim().toUpperCase(),metaPixelId:$("metaPixelId").value.trim(),tiktokPixelId:$("tiktokPixelId").value.trim(),mailchimpScriptUrl:$("mailchimpScriptUrl").value.trim()};}
  function validHttpUrl(value,host){if(!value)return true;try{var u=new URL(value);return u.protocol==="https:"&&(!host||u.hostname===host||u.hostname.endsWith("."+host));}catch(e){return false;}}
  function validateIntegration(){readIntegrationForm();var i=state.integrations;if(i.sheetsEnabled&&!/^https:\/\/script\.google\.com\/macros\/s\/.+\/exec(?:\?.*)?$/i.test(i.sheetsWebhookUrl))return "Bật Google Sheets cần một Apps Script Web App URL kết thúc bằng /exec.";if(i.sheetDocumentUrl&&!validHttpUrl(i.sheetDocumentUrl,"docs.google.com"))return "Link Google Sheet phải là URL HTTPS của docs.google.com.";if(i.trackingEnabled&&i.gtmId&&!/^GTM-[A-Z0-9]+$/.test(i.gtmId))return "GTM ID chưa đúng định dạng GTM-XXXXXXX.";if(i.trackingEnabled&&i.ga4Id&&!/^G-[A-Z0-9]+$/.test(i.ga4Id))return "GA4 ID chưa đúng định dạng G-XXXXXXXXXX.";if(i.trackingEnabled&&i.metaPixelId&&!/^\d{5,30}$/.test(i.metaPixelId))return "Meta Pixel ID chỉ gồm chữ số.";if(i.mailchimpScriptUrl&&!validHttpUrl(i.mailchimpScriptUrl,"chimpstatic.com"))return "Mailchimp script phải là URL HTTPS thuộc chimpstatic.com.";return "";}
  function updateIntegrationHealth(){var el=$("sheetHealth"),i=state.integrations||{};if(!i.sheetsEnabled){el.className="notice neutral";el.textContent="Đồng bộ Google Sheets đang tắt. Lead vẫn được lưu an toàn trong Firestore.";}else if(!i.sheetsWebhookUrl){el.className="notice warn";el.textContent="Đã bật nhưng chưa có Web App URL; chưa thể ghi thêm dòng vào Sheet.";}else{el.className="notice ok";el.textContent="Sẵn sàng gửi bản sao lead đến tab “"+(i.sheetTabName||"chưa đặt tên")+"”. Firestore vẫn là nguồn dữ liệu chính.";}}
  $("saveIntegrationDraftBtn").onclick=async function(){var error=validateIntegration();if(error)return toast(error,true);try{await db.collection("cms_drafts").doc(state.pageId).set(editorPayload(),{merge:true});state.integrationDirty=false;$("integrationState").textContent="Đã lưu bản nháp";$("integrationState").classList.remove("integration-dirty");toast("Đã lưu nháp SEO và cấu hình tích hợp.");}catch(e){toast(errorMessage(e),true);}};
  $("publishIntegrationBtn").onclick=async function(){var error=validateIntegration();if(error)return toast(error,true);if(!confirm("Xuất bản SEO và cấu hình tích hợp lên "+cfg.pages[state.pageId].name+"?"))return;try{var batch=db.batch(),payload=editorPayload();batch.set(db.collection("cms_public").doc(state.pageId),payload);batch.set(db.collection("cms_drafts").doc(state.pageId),payload,{merge:true});batch.set(db.collection("cms_versions").doc(state.pageId).collection("items").doc(),{content:state.content,seo:state.seo,integrations:state.integrations,createdAt:FV.serverTimestamp(),createdBy:state.user.email});await batch.commit();state.integrationDirty=false;$("integrationState").textContent="Đã xuất bản";$("integrationState").classList.remove("integration-dirty");sendPreview();toast("Đã xuất bản cấu hình. LDP sẽ áp dụng khi tải lại.");}catch(e){toast(errorMessage(e),true);}};

  $("leadPage").onchange = loadLeads; $("leadSearch").oninput = renderLeads; $("leadStatus").onchange = renderLeads; $("refreshLeads").onclick = loadLeads;
  async function loadLeads() { var pageId=$("leadPage").value; $("leadRows").innerHTML='<tr><td colspan="6" class="empty">Đang tải…</td></tr>'; try { var snap=await db.collection(cfg.pages[pageId].collection).orderBy("submittedAt","desc").limit(300).get(); state.leads=[]; snap.forEach(function(doc){state.leads.push(Object.assign({_id:doc.id,_pageId:pageId},doc.data()));}); renderLeads(); } catch(e){toast(errorMessage(e),true);} }
  function renderLeads() { var q=($("leadSearch").value||"").toLowerCase(), s=$("leadStatus").value; var rows=state.leads.filter(function(l){var hay=[l.fullname,l.phone,l.email,l.company,l.utm_source,l.utm_campaign,l.gclid,l.fbclid,l.fbc,l.fbp,l.ttclid].join(" ").toLowerCase(); return (!q||hay.indexOf(q)>=0)&&(!s||(l.cms_status||"new")===s);}); $("leadCount").textContent=rows.length+" / "+state.leads.length+" lead (tối đa 300 bản ghi gần nhất)"; $("leadRows").innerHTML=rows.map(function(l){var click=l.gclid||l.fbclid||l.ttclid||l.msclkid||"";return '<tr data-id="'+esc(l._id)+'"><td><strong>'+esc(l.fullname)+'</strong><small>'+esc(l.email||"—")+'</small></td><td>'+esc(l.phone||"—")+'</td><td>'+esc(l.company||"—")+'</td><td><strong>'+esc(l.utm_source||"Trực tiếp")+'</strong><small>'+esc(click||l.utm_campaign||"—")+'</small></td><td>'+time(l.submittedAt)+'</td><td><span class="badge '+esc(l.cms_status||"new")+'">'+esc(statusLabel(l.cms_status))+'</span></td></tr>';}).join("")||'<tr><td colspan="6" class="empty">Không có kết quả.</td></tr>'; $("leadRows").querySelectorAll("tr[data-id]").forEach(function(row){row.onclick=function(){openLead(row.dataset.id);};}); }
  function openLead(id) { var l=state.leads.find(function(x){return x._id===id;}); if(!l)return; state.leadRef=l; $("leadDialogTitle").textContent=l.fullname||"Lead"; var keys=["phone","email","company","industry","budget","report_focus","signal_score","weakest_dimension","utm_source","utm_medium","utm_campaign","utm_content","utm_term","gclid","fbclid","fbc","fbp","ttclid","pageUrl","referrer"]; $("leadDetail").innerHTML=keys.filter(function(k){return l[k]!==undefined&&l[k]!=="";}).map(function(k){return '<div class="detail-item"><span>'+esc(k)+'</span><div>'+esc(l[k])+'</div></div>';}).join(""); $("editLeadStatus").value=l.cms_status||"new"; $("editLeadOwner").value=l.cms_owner||""; $("editLeadNotes").value=l.cms_notes||""; $("leadDialog").showModal(); }
  $("saveLeadBtn").onclick = async function () { var l=state.leadRef;if(!l)return;try{var update={cms_status:$("editLeadStatus").value,cms_owner:$("editLeadOwner").value.trim(),cms_notes:$("editLeadNotes").value.trim(),cms_updatedAt:FV.serverTimestamp(),cms_updatedBy:state.user.email};await db.collection(cfg.pages[l._pageId].collection).doc(l._id).update(update);Object.assign(l,update);$("leadDialog").close();renderLeads();loadDashboard();toast("Đã cập nhật lead.");}catch(e){toast(errorMessage(e),true);} };
  $("exportBtn").onclick = function () { var rows=state.leads;if(!rows.length)return toast("Không có dữ liệu để xuất.",true);var fields=Array.from(rows.reduce(function(set,row){Object.keys(row).filter(function(k){return k[0]!=="_";}).forEach(function(k){set.add(k);});return set;},new Set()));function cell(v){if(v&&v.toDate)v=time(v);v=String(v==null?"":v);if(/^[=+\-@]/.test(v))v="'"+v;return '"'+v.replace(/"/g,'""')+'"';}var csv="\ufeff"+fields.map(cell).join(",")+"\r\n"+rows.map(function(r){return fields.map(function(f){return cell(r[f]);}).join(",");}).join("\r\n");var a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=cfg.pages[$("leadPage").value].collection+"-"+new Date().toISOString().slice(0,10)+".csv";a.click();URL.revokeObjectURL(a.href); };

  $("versionPage").onchange=loadVersions;$("refreshVersions").onclick=loadVersions;
  async function loadVersions(){var pageId=$("versionPage").value;$("versionList").innerHTML='<div class="empty">Đang tải…</div>';try{var snap=await db.collection("cms_versions").doc(pageId).collection("items").orderBy("createdAt","desc").limit(30).get(),items=[];snap.forEach(function(d){items.push(Object.assign({_id:d.id},d.data()));});$("versionList").innerHTML=items.map(function(v,i){return '<div class="version-item"><div><h4>Bản '+esc(v._id.slice(0,8))+(i===0?' · Mới nhất':'')+'</h4><p class="muted">'+time(v.createdAt)+' · '+esc(v.createdBy||"—")+' · '+Object.keys(v.content||{}).length+' trường</p></div><button class="btn btn-secondary" data-version="'+esc(v._id)+'">Khôi phục về nháp</button></div>';}).join("")||'<div class="empty">Chưa có phiên bản đã xuất bản.</div>';$("versionList").querySelectorAll("[data-version]").forEach(function(b){b.onclick=function(){restoreVersion(pageId,items.find(function(v){return v._id===b.dataset.version;}));};});}catch(e){toast(errorMessage(e),true);}}
  async function restoreVersion(pageId,v){if(!v||!confirm("Khôi phục phiên bản này về bản nháp?"))return;try{await db.collection("cms_drafts").doc(pageId).set({content:v.content||{},seo:v.seo||{},integrations:v.integrations||defaultIntegrations(pageId),updatedAt:FV.serverTimestamp(),updatedBy:state.user.email,restoredFrom:v._id},{merge:true});$("contentPage").value=pageId;$("integrationPage").value=pageId;await loadContent(pageId);showView("content");toast("Đã khôi phục nội dung, SEO và tích hợp về bản nháp. Hãy xem thử rồi xuất bản.");}catch(e){toast(errorMessage(e),true);}}

  $("adminForm").onsubmit=async function(e){e.preventDefault();var data=new FormData(e.target),uid=String(data.get("uid")).trim();try{await db.collection("cms_admins").doc(uid).set({email:String(data.get("email")).trim().toLowerCase(),role:data.get("role"),active:true,updatedAt:FV.serverTimestamp(),updatedBy:state.user.email},{merge:true});e.target.reset();loadTeam();toast("Đã cấp quyền thành viên.");}catch(err){toast(errorMessage(err),true);}};
  async function loadTeam(){if(!state.user)return;try{var snap=await db.collection("cms_admins").get(),items=[];snap.forEach(function(d){items.push(Object.assign({_id:d.id},d.data()));});items.sort(function(a,b){return String(a.email).localeCompare(String(b.email));});$("adminList").innerHTML=items.map(function(a){return '<div class="admin-item"><div><h4>'+esc(a.displayName||a.email||a._id)+'</h4><p class="muted">'+esc(a.email||"")+' · '+esc(a.role||"editor")+' · '+(a.active===false?'Đã tắt':'Đang hoạt động')+'</p></div><div class="admin-actions"><span class="badge '+(a.active===false?'lost':'won')+'">'+(a.active===false?'Tắt':'Active')+'</span><button class="btn btn-ghost" data-admin="'+esc(a._id)+'" data-active="'+(a.active===false?'true':'false')+'">'+(a.active===false?'Bật':'Tắt')+'</button></div></div>';}).join("")||'<div class="empty">Chưa có thành viên.</div>';$("adminList").querySelectorAll("[data-admin]").forEach(function(b){b.onclick=async function(){try{await db.collection("cms_admins").doc(b.dataset.admin).update({active:b.dataset.active==="true",updatedAt:FV.serverTimestamp(),updatedBy:state.user.email});loadTeam();}catch(e){toast(errorMessage(e),true);}};});}catch(e){toast(errorMessage(e),true);}}
})();
